name: Python Lint

on:
  push:
    branches: [main]
    paths:
      - 'scripts/**/*.py'
      - '.github/workflows/python-lint.yml'
  pull_request:
    branches: [main]
    paths:
      - 'scripts/**/*.py'
      - '.github/workflows/python-lint.yml'

jobs:
  lint:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13.5'

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install black flake8 pandas

      - name: Run Black (check formatting)
        run: black --check scripts

      - name: Run Flake8 (linting)
        run: flake8 scripts
